# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Use Python 3.10+ to satisfy mcp[cli] requirements
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy dependency file
COPY requirements.txt ./

# Upgrade pip and install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Ensure run_server.sh is executable
RUN chmod +x run_server.sh

# Default command to start the MCP server via stdio
CMD ["./run_server.sh"]
